name: Update Production Server
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Update Frontend
      uses: appleboy/ssh-action@master
      with:
        host: 8.9.4.246
        username: fandemic
        key: ${{secrets.SSH_SERVER}}
        port: 22
        script: |
          cd CS330-NetworkingProject
          git pull origin master
          git status
